create database Adidas_sales;

use Adidas_sales;

alter table `adidas us sales datasets`
rename adidas_sales;

select * from adidas_sales;

ALTER TABLE adidas_sales
RENAME COLUMN `Retailer ID` TO Retailer_ID,
RENAME COLUMN `Invoice Date` TO Invoice_Date,
RENAME COLUMN `Price per Unit` TO Price_Per_Unit,
RENAME COLUMN `Units Sold` TO Units_Sold,
RENAME COLUMN `Total Sales` TO Total_Sales,
RENAME COLUMN `Operating Profit` TO Operating_Profit,
RENAME COLUMN `Operating Margin` TO Operating_Margin,
RENAME COLUMN `Sales Method` TO Sales_Method;

UPDATE adidas_sales
SET 
price_per_unit = CAST(REPLACE(price_per_unit, '$', '') AS DECIMAL(10,2)),
total_sales = CAST(REPLACE(total_sales, '$', '') AS DECIMAL(10,2)),
operating_profit = CAST(REPLACE(operating_profit, '$', '') AS DECIMAL(10,2)),
operating_margin = CAST(REPLACE(operating_margin, '%', '') AS DECIMAL(5,2))/100;


SHOW COLUMNS FROM adidas_sales;


## Section 1: Executive KPIs
-- Query 1: What is the total revenue and total operating profit generated by Adidas?
select sum(Total_Sales) as Total_revenue,
	   sum(Operating_Profit)as total_Operating_Profit
       from adidas_sales;


-- Query 2:What is the total volume of units sold across all retailers?
select sum(Units_Sold) as Total_Units_Sold
from adidas_sales;


-- Query 3:What is the overall average operating margin (%) for the business?
select sum(Operating_Margin)as AVG_Operating_Margin
from adidas_sales;

## Section 2: Product Performance Analysis

-- Query 4:Which are the top 5 products contributing the highest revenue?
select Product,
    sum(Total_Sales) as Total_Revenue
from adidas_sales
group by Product
order by Total_Revenue desc
limit 5;

-- Query 5:Which product category has the lowest sales volume?
select Product,
    sum(Units_Sold) as Total_Units_Sold
from adidas_sales
group by Product
order by Total_Units_Sold asc
limit 1;


-- Query 6:What is the average price per unit for each product category?
select Product, avg(Price_Per_Unit) as Avg_Price_Per_Unit
from adidas_sales
group by Product;

## Section 3: Retailer & Regional Insights

-- Query 7:Who are the top 3 retailers based on total sales?
select ﻿Retailer,
       Retailer_ID,
	   sum(Total_Sales) as Total_Saless
from adidas_sales
group by Retailer
order by Total_Saless desc
limit 3;

-- Query 8:Which state contributes the highest revenue?
select State,
       sum(Total_Sales) as Highest_revenue
from adidas_sales
group by state;

-- Query 9:What is the percentage contribution of each region to total sales?
select Region,
       sum(Total_Sales) as Highest_revenue
from adidas_sales
group by Region;

## Section 4: Sales Method & Channel Efficiency

-- Query 10:How does in-store sales compare with online and outlet sales?
select 
   Sales_Method,
    sum(Total_Sales) as total_sales
from adidas_sales
group by Sales_Method
order by  Total_Sales desc;

-- Query 11:Which sales method has the highest operating margin (%)?
select 
    Sales_Method,
    sum(Operating_Margin) as avg_Operating_Margin
from adidas_sales
group by Sales_Method
order by avg_Operating_Margin desc
limit 1;

-- Query 9:Which city has the highest average price per unit?


## Section 5: Time-Series & Trends
-- Query 12:Which month recorded the highest sales, indicating peak season?
select
    month(Invoice_Date) as Month,
    SUM(Total_Sales)as Total_Sales
FROM adidas_sales
group by Month
order by Total_Sales desc
limit 1;




